### ISSUE TITLE
Preferences menu can be tall enough to move the "done" button off screen

### ISSUE THREAD

**Issue by jennraeross** [kmwallio/ThiefMD#68]
current screen resolution is 1440 * 810

![Screenshot from 2020-10-11 15-34-29](https://user-images.githubusercontent.com/44242181/95690772-53fe9700-0bd7-11eb-8054-2caf96292f24.png)

**Comment by kmwallio** [comment]
Thanks for letting me know, I'll look into fixing this for the next release.

**Comment by kmwallio** [comment]
I added a scrollbar to the Export Tab to reduce the height and made the window resizable and closable from the top bar.

![image](https://user-images.githubusercontent.com/132455/95691504-7a6f0300-0bd4-11eb-9828-86ceb35c00eb.png)

This will go out in the next release, but @jennraeross can you check the "Display" tab to make sure it's not extending offscreen as well?

I'll leave this issue open until the fix is shipped, but for those having this issue, hitting the `Esc` key will close the preferences window.

**Comment by jennraeross** [comment]
The display tab's content doesn't extend down that far, so this should do it, thanks!
