### ISSUE TITLE
Implement Libhandy

### ISSUE THREAD

**Issue by anthonyajumelles** [kmwallio/ThiefMD#88]
Implementing libhandy will be useful for ensuring ThiefMD is usable at smaller widths and on mobile devices like the Librem5/Pinephone

https://gitlab.gnome.org/GNOME/libhandy/

![Screenshot from 2020-10-28 03-33-48](https://user-images.githubusercontent.com/62868183/97405868-b8f00780-18ce-11eb-9220-c74fa3128f93.png)
![Screenshot from 2020-10-28 03-33-33](https://user-images.githubusercontent.com/62868183/97405871-b9889e00-18ce-11eb-97e8-6a83e2ea68b6.png)

Current behaviour with word wrap is non-ideal due to text being cut off at low width.

A good example of how best to implement this would be [NewsFlash](https://gitlab.com/news-flash/news_flash_gtk).

![Screenshot from 2020-10-28 03-37-08](https://user-images.githubusercontent.com/62868183/97406095-11270980-18cf-11eb-87b8-12b31359bd93.png)
![Screenshot from 2020-10-28 03-37-05](https://user-images.githubusercontent.com/62868183/97406096-11270980-18cf-11eb-9db2-e2fbaf1dd533.png)
![Screenshot from 2020-10-28 03-37-02](https://user-images.githubusercontent.com/62868183/97406099-11bfa000-18cf-11eb-90cf-09ef9b83d0ea.png)

**Comment by kmwallio** [comment]
I won't be able to get to this until mid-November or later. (Although my Pine Phone arrives next week, so NaNoWriMo might be going out the window when it's here...)

Thanks for the pointer to News Flash! I think I've only seen 2 column layout demos, so this will be useful as I dig in further on what changes should be done and what is possible.

## Brain dump follows

This requires changing [Application.vala](https://github.com/kmwallio/ThiefMD/blob/master/src/Application.vala) into 2 new parts. The construction of the main window should be moved into a new file that extends [Hdy.ApplicationWindow](https://valadoc.org/libhandy-1/Hdy.ApplicationWindow.html), the rest of the contents and state can stay in Application.vala.

Things to change to [Hdy.Window](https://valadoc.org/libhandy-1/Hdy.Window.html)
* [SearchWindow.vala](https://github.com/kmwallio/ThiefMD/blob/master/src/Widgets/SearchWindow.vala)
* [PublisherPreview.vala](https://github.com/kmwallio/ThiefMD/blob/master/src/Widgets/PublisherPreviewWindow.vala)
* [PreviewWindow.vala](https://github.com/kmwallio/ThiefMD/blob/master/src/Widgets/PreviewWindow.vala)
* [MarkdownCheatSheet.vala](https://github.com/kmwallio/ThiefMD/blob/master/src/Widgets/MarkdownCheatSheet.vala)

*I need to learn the pattern for mobile apps. **TBD:** Can these stay in separate windows, or should these populate the main application window on mobile?*

Things to change to [Hdy.Headerbar](https://valadoc.org/libhandy-1/Hdy.HeaderBar.html)
* [SearchWindow.vala](https://github.com/kmwallio/ThiefMD/blob/master/src/Widgets/SearchWindow.vala)
* [PublisherPreview.vala](https://github.com/kmwallio/ThiefMD/blob/master/src/Widgets/PublisherPreviewWindow.vala)
* [MarkdownCheatSheet.vala](https://github.com/kmwallio/ThiefMD/blob/master/src/Widgets/MarkdownCheatSheet.vala)

***TBD:** Do these maintain their own headerbar, or do they update a common headerbar when displayed on mobile?*

The flatpak manifest will need:
```json
{
    "name" : "libhandy",
    "buildsystem" : "meson",
    "config-opts" : [
        "-Dexamples=false",
        "-Dprofiling=false",
        "-Dglade_catalog=disabled",
        "-Dintrospection=enabled",
        "-Dtests=false",
        "-Dvapi=false"
    ],
    "sources" : [
        {
            "type": "archive",
            "url": "https://download.gnome.org/sources/libhandy/1.0/libhandy-1.0.0.tar.xz",
            "sha256": "a9398582f47b7d729205d6eac0c068fef35aaf249fdd57eea3724f8518d26699"
        }
    ]
},
```

For responsiveness, [there's a guide here](https://tuxphones.com/tutorial-developing-responsive-linux-smartphone-apps-gnome-builder-gtk-libhandy-gtk-part-1/). Responsiveness will be a bigger change since I think everything should be displayed in a single window.

Additional Resources:
* [Adaptive View Switcher for Preferences](https://puri.sm/posts/the-new-libhandy-0-0-10/), [Hdy.PreferencesWindow](https://gnome.pages.gitlab.gnome.org/libhandy/HdyPreferencesWindow.html)
* [Hdy.SearchBar](https://valadoc.org/libhandy-1/Hdy.SearchBar.html)
* [Hdy.Leaflet](https://blogs.gnome.org/alexm/2019/12/12/gnome-and-gestures-part-3-hdyleaflet-again/) for Library and Sheets view to allow for a single column view.
* [Blog post on HeaderBars and Views](https://blogs.gnome.org/alexm/2020/04/12/on-windows-and-titlebars/)

**Comment by kmwallio** [comment]
Started branch [libhandy](https://github.com/kmwallio/ThiefMD/tree/libhandy). For some reason, Hdy.Headerbar isn't dragging from inside the Gtk.Box even though to documentation says it should? I'll have to investigate when I get more time.

**Comment by BrainBlasted** [comment]
You need the run `Hdy.init()` (IIRC that's how it's called in vala) after GTK init or in your application startup function.

**Comment by kmwallio** [comment]
@BrainBlasted thank you so much for sharing! The headerbar now drags, and libhandy's round corners fix a lot of the GTK graphics issues.

![Handy's round corners on ThiefMD](https://user-images.githubusercontent.com/132455/97784681-7db73800-1b5d-11eb-80c1-795b43719210.png)

**Comment by kmwallio** [comment]
Still a lot of work to do, but Preferences and Editor are responsive and usable-ish on mobile :grinning: 

![ThiefMD Editor on Mobile](https://user-images.githubusercontent.com/132455/98338494-1f57e280-1fbf-11eb-9773-a9886f382f3c.jpeg)

![ThiefMD Preferences on Mobile](https://user-images.githubusercontent.com/132455/98338513-27b01d80-1fbf-11eb-8ec4-450211229a26.jpeg)

**Comment by davidbosman** [comment]
I'm not a dev so I'm, not sure it is related but there is this issue I have while using ThiefMD on a big screen (1920x1200): in the Library, I often myself unable to read both the fodler names in ther entirety *and* the file names at the same time.  I can either see the full name of every folder, but not the name of the files they contain. Or if I can shrink the folder pane (and cut folder's names) in order to see the complet name of files. 

The issue seems to be that the side panel can't be extended fiurther to the right than a certain fixed width, despite me having more than enough free pixels (1920x1200) to make it as big as I need while stil displaying some text on the right side.

Note that because of a bad eyesight, I use somewhat bigger than usualfonts everywhere on my Xfce box, and use IA Writer Duo Font size 20 in ThiefMD's preferences.

Let me know if that is normal behavior or if it something you'd rather have listed as a new issue/suggestion and if you need any more information). I'll be glad to help if I can ;)

**Comment by kmwallio** [comment]
> The issue seems to be that the side panel can't be extended fiurther to the right than a certain fixed width, despite me having more than enough free pixels (1920x1200) to make it as big as I need while stil displaying some text on the right side.

Thanks for bringing this up! This is a bug/regression. I'll figure out what's causing it and get a fix in the next release.
