### ISSUE TITLE
Feature request: Give an option in settings, to always start with a new, blank sheet created, each time when the app is opened

### ISSUE THREAD

**Issue by marek-lach** [kmwallio/ThiefMD#97]
This would be useful for noting down passing ideas quickly. iaWriter used to have a functionality like this once.

**Comment by kmwallio** [comment]
Thank you for the suggestion. I know I miss taking notes during meetings because I need to create a new sheet and pick a filename :sweat_smile: 

I'm trying to think and flesh this one out more. I know certain editors use the first few words, or the first `# Title` as an auto-generated file name.

If user's only use ThiefMD to manage their writing, the file names aren't too important. For users who sync using Dropbox or something similar, picking a meaningful filename is important.

Would you want to be prompted for a file name when you switch to another sheet/close the app, or should the app determine a file name and save it in the selected library folder?

**Comment by marek-lach** [comment]
> I know certain editors use the first few words, or the first # Title as an auto-generated file name.

Yes.

> Would you want to be prompted for a file name...?

I think that would be just fine, and probably also easier to implement, than any other variant.

Thanks for considering this.

**Comment by davidbosman** [comment]
You cold also use Date-Time as a default filename if none is provided or if the user would rather decide of of a name later on? 

Doing so twould make any "quick" note easily findable ('I wrote that during the meeting last Friday morning') and would also avoid conflicting file names if the user is not to keen on naming files ;)

**Comment by kmwallio** [comment]
> You could also use Date-Time as a default filename if none is provided

Thank you for this suggestion. It's simple, but also provides context outside of the editor.

I'll start working on this after the next release. I've been practicing taking notes at every meeting, and with how fast paced some are, I miss parts or have to search to find out what file I overlapped meetings on.

**Comment by kmwallio** [comment]
Just as an update, I've started work on this.

![Start with new empty sheet](https://user-images.githubusercontent.com/132455/111922602-ff015f80-8a57-11eb-9f69-a9625aec2f98.gif)

It will save as `YYYY-MM-DD-first-four-valid-words.md` or `YYYY-MM-DD_HH-MM-SS.md` if valid words consisting of valid file name characters cannot be found.

I'm currently working on making sure file names wind up valid (like if you open and paste a long URL, base64 encoded certificate, or really long words). If I'm not too confident, I might remove the pretty naming until I think it's suitable.

But this should be appearing in settings withing the next couple of weeks. If the Library is empty, the Tips page will show. Whenever you start typing, it will save to the currently selected Folder in the Library (defaulting to the last directory you were working in).

Thank you for your patience and additional suggestions helping to bring this feature to life :smile:
